title: Wunderlich
permalink: /:title/

# Build settings
kramdown:
    input: GFM
    parse_block_html: false
sass:
    sass_dir: /assets/styles/
    style: compressed

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: ""